import test from 'node:test';
import assert from 'node:assert/strict';
import { handleContact, destination } from './handler.mjs';
const input={email:'visitor@institution.org',message:'Un proyecto científico — gracias.',token:'test-token'};
const request=(data=input,origin='https://leolaguna.com')=>new Request('https://leolaguna.com/api/contact',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(data)});
const env=()=>({TURNSTILE_SECRET_KEY:'test-only-not-a-real-secret',CONTACT_FROM:'forms@leolaguna.com',EMAIL:{send(){}},CONTACT_RATE_LIMITER:{async limit(){return {success:true};}}});
const setup=(validation={success:true,action:'contact',hostname:'leolaguna.com'})=>{const calls=[];return {calls,deps:{async verify(payload){calls.push(['verify',payload]);return validation;},async deliver(message){calls.push(['send',message]);}}};};
test('verified submission uses private destination and visitor Reply-To',async()=>{const {calls,deps}=setup();const result=await handleContact(request(),env(),deps);assert.equal(result.status,200);assert.equal(calls[0][1].response,'test-token');assert.equal(calls[1][1].to,destination);assert.equal(calls[1][1].replyTo,input.email);assert.equal(calls[1][1].text,input.message);});
for(const [name,validation] of [['forged token',{success:false}],['wrong action',{success:true,action:'other',hostname:'leolaguna.com'}],['wrong hostname',{success:true,action:'contact',hostname:'evil.test'}]])test(name+' never sends email',async()=>{const {calls,deps}=setup(validation);assert.equal((await handleContact(request(),env(),deps)).status,400);assert.equal(calls.filter(x=>x[0]==='send').length,0);});
for(const [name,data] of [['header injection',{...input,email:'a@b.com\r\nBcc: other@evil.com'}],['long message',{...input,message:'a'.repeat(501)}],['empty message',{...input,message:' '}],['invalid email',{...input,email:'invalid'}],['missing token',{...input,token:''}]])test(name+' rejected before Siteverify',async()=>{const {calls,deps}=setup();assert.equal((await handleContact(request(data),env(),deps)).status,400);assert.equal(calls.length,0);});
test('missing email binding fails closed',async()=>{const config=env();delete config.EMAIL;const {calls,deps}=setup();assert.equal((await handleContact(request(),config,deps)).status,503);assert.equal(calls.length,0);});
test('foreign origin rejected',async()=>{const {calls,deps}=setup();assert.equal((await handleContact(request(input,'https://evil.test'),env(),deps)).status,403);assert.equal(calls.length,0);});
test('rate limited request never verifies or sends',async()=>{const config=env();config.CONTACT_RATE_LIMITER.limit=async()=>({success:false});const {calls,deps}=setup();assert.equal((await handleContact(request(),config,deps)).status,429);assert.equal(calls.length,0);});
test('oversized body rejected',async()=>{const {calls,deps}=setup();assert.equal((await handleContact(request({...input,extra:'x'.repeat(9000)}),env(),deps)).status,413);assert.equal(calls.length,0);});
test('delivery failure is not success',async()=>{const {deps}=setup();deps.deliver=async()=>{throw Error('offline');};assert.equal((await handleContact(request(),env(),deps)).status,503);});

test('populated honeypot never verifies or sends',async()=>{const {calls,deps}=setup();assert.equal((await handleContact(request({...input,website:'bot'}),env(),deps)).status,400);assert.equal(calls.length,0);});
